ViewModels/CarsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data.Models;

namespace WebStore.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> AllCars { get; set; }

        public string CurrCategorry { get; set; }

    }
}

ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data.Models;

namespace WebStore.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> FavCars { get; set; }
    }
}

ViewModels/StoreCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data.Models;

namespace WebStore.ViewModels
{
    public class StoreCartViewModel
    {
        public StoreCart StoreCart { get; set; }

    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Data.Interfaces;
using WebStore.Data.Models;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars allCars;
        private readonly ICarsCategory allCategories;

        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
        {
            allCars = iAllCars;
            allCategories = iCarsCat;
        }
        
        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = allCars.Cars.OrderBy(c => c.Id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = allCars.Cars.Where(c => c.Category.Name.Equals("Electric cars")).OrderBy(c => c.Id);
                    currCategory = "Electro cars";
                }
                else 
                {
                    cars = allCars.Cars.Where(c => c.Category.Name.Equals("Cars")).OrderBy(c => c.Id);
                    currCategory = "Fuel cars";
                }
                
                
            }
            var carObj = new CarsListViewModel
            {
                AllCars = cars,
                CurrCategorry = currCategory
            };
            ViewBag.Title = "Car's Page"; 
            return View(carObj);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data.Interfaces;
using WebStore.Data.Models;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars _carRep;

        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
        }
        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                FavCars = _carRep.GetFavCars
            };
            return View(homeCars);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Data;
using WebStore.Data.Interfaces;
using WebStore.Data.Models;

namespace WebStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllorders allorders;
        private readonly StoreCart storeCart;
        public OrderController(IAllorders allorders, StoreCart storeCart)
        {
            this.allorders = allorders;
            this.storeCart = storeCart;
        }

        public IActionResult Checkout()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            storeCart.ListStoreItems = storeCart.GetStoreItems();
            if(storeCart.ListStoreItems.Count == 0)
            {
                ModelState.AddModelError("","You should add to cart something!");
            }
            if (ModelState.IsValid)
            {
                allorders.CreateOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Order complete! Our manager will call You soon. Thanks.";
            return View();
        }
    }
}

Controllers/StoreCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.Data.Interfaces;
using WebStore.Data.Models;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class StoreCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly StoreCart _storeCart;
        
        public StoreCartController(IAllCars carRep, StoreCart storeCart)
        {
            _carRep = carRep;
            _storeCart = storeCart;
        }

        public ViewResult Index()
        {
            var items = _storeCart.GetStoreItems();
            _storeCart.ListStoreItems = items;
            var obj = new StoreCartViewModel
            {
                StoreCart = _storeCart
            };
            return View(obj);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.Id == id);
            if(item != null)
            {
                _storeCart.AddToCart(item);
            }
            return RedirectToAction("Index");

        }
    }
}

Views/Cars/List.cshtml
<h1>All cars</h1>
<h3>@Model.CurrCategorry</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.AllCars)
        {
            @Html.Partial("AllCars", car)
        }
        }

</div>

Views/Home/Index.cshtml
@model HomeViewModel
<h1>Best cars</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.FavCars)
        {
            @Html.Partial("AllCars", car)
        }
    }

</div>

Views/Order/Checkout.cshtml
@model Order

    <div class="row-cols-lg-1">
        <h3>Ordering</h3>
        <form asp-action="Checkout" method="Post" class="form-check-label">
            <div class="form-group">
                <label asp-for="Name"></label>
                <div class="col-md-5">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Surname"></label>
                <div class="col-md-5">
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <div class="col-md-5">
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Phone"></label>
                <div class="col-md-5">
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <div class="col-md-5">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <input class="btn btn-success" type="submit" value="Finish order" />
        </form>
    </div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.ShortDescription</p>
    <p>Price: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="StoreCart" asp-action="AddToCart" asp-route-Id="@Model.Id">Add to Cart</a></p>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/Style.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">AutoLover</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Main<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List">All cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/electro">Electro cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/fuel">Fuel cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/StoreCart/">Cart</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Find your car" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <hr />
    <hr />
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Artur Olenych
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Views/StoreCart/Index.cshtml
@model StoreCartViewModel
    <div class="container">
        @foreach (var el in Model.StoreCart.ListStoreItems)
        {
            <div class="alert alert-warning mt-3">
                <b>Car:</b> @el.Car.Name <br />
                <b>Price:</b> @el.Car.Price.ToString("c")
            </div>
        }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Buy</a>
    </div>